### PR TITLE
openal: openal-soft.org outages, switch to use their GitHub repository

### PR DESCRIPTION
**Pull request by RegDogg**
https://openal-soft.org/ seems to have been having outages, or is just permanently down.

I feel their GitHub repository is the best alternative to it.

### CODE REVIEW

**Comment by RegDogg** [comment]
Closing PR because the issue doesn't seem to recur as often as I expected.

**Comment by RegDogg** [comment]
Was told that @Maxwell175 may be planning to merge this Pull Request, thus it has been reopened.

**Comment by Maxwell175** [comment]
Would you mind also updating the URLs for the other platforms?

**Comment by RegDogg** [comment]
> Would you mind also updating the URLs for the other platforms?

Done

**Pull request merged**
